add_library(${PROJECT_NAME} INTERFACE)

target_include_directories(
    ${PROJECT_NAME}
    INTERFACE
        "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/public>"
        "$<INSTALL_INTERFACE:include>"
)

target_link_libraries(
    ${PROJECT_NAME}
    INTERFACE
        UnrealVoxelSim.Events.Api
        UnrealVoxelSim.Simulation.Api
        UnrealVoxelSim.Voxel.Api
)

UnrealVoxelSimConfigureTarget(${PROJECT_NAME})
